# Generated by Django 3.2.12 on 2023-06-21 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elasticsearchdjgo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
