# Generated by Django 3.2.12 on 2023-06-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_delivered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
