# Generated by Django 3.2.12 on 2023-06-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_order_delivered_date'),
        ('order', '0013_auto_20230618_0201'),
    ]

    operations = [
    ]
