# Generated by Django 3.2.12 on 2023-06-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_merge_20230619_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
