# Generated by Django 3.2.12 on 2023-06-25 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_order_status'),
        ('order', '0016_order_customer'),
    ]

    operations = [
    ]
